server:
  port: 8081

spring:
  application:
    name: auth-service

datasource:
  url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  driverClassName: org.h2.Driver
  username: sa
  password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    private-key: ${JWT_PRIVATE_KEY_PATH}
    public-key: ${JWT_PUBLIC_KEY_PATH}
    access-expiration: 15m
    refresh-expiration: 7d
    issuer: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/