server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/tasks/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/